#
#
#

MBEDTLS_OBJ += $(MBEDTLS_LIB_DIR)/library/aes.o \
$(MBEDTLS_LIB_DIR)/library/aesni.o \
$(MBEDTLS_LIB_DIR)/library/arc4.o \
$(MBEDTLS_LIB_DIR)/library/asn1parse.o \
$(MBEDTLS_LIB_DIR)/library/asn1write.o \
$(MBEDTLS_LIB_DIR)/library/base64.o \
$(MBEDTLS_LIB_DIR)/library/bignum.o \
$(MBEDTLS_LIB_DIR)/library/blowfish.o \
$(MBEDTLS_LIB_DIR)/library/camellia.o \
$(MBEDTLS_LIB_DIR)/library/ccm.o \
$(MBEDTLS_LIB_DIR)/library/certs.o \
$(MBEDTLS_LIB_DIR)/library/cipher.o \
$(MBEDTLS_LIB_DIR)/library/cipher_wrap.o \
$(MBEDTLS_LIB_DIR)/library/cmac.o \
$(MBEDTLS_LIB_DIR)/library/ctr_drbg.o \
$(MBEDTLS_LIB_DIR)/library/debug.o \
$(MBEDTLS_LIB_DIR)/library/des.o \
$(MBEDTLS_LIB_DIR)/library/dhm.o \
$(MBEDTLS_LIB_DIR)/library/ecdh.o \
$(MBEDTLS_LIB_DIR)/library/ecdsa.o \
$(MBEDTLS_LIB_DIR)/library/ecjpake.o \
$(MBEDTLS_LIB_DIR)/library/ecp.o \
$(MBEDTLS_LIB_DIR)/library/ecp_curves.o \
$(MBEDTLS_LIB_DIR)/library/entropy.o \
$(MBEDTLS_LIB_DIR)/library/entropy_poll.o \
$(MBEDTLS_LIB_DIR)/library/error.o \
$(MBEDTLS_LIB_DIR)/library/gcm.o \
$(MBEDTLS_LIB_DIR)/library/havege.o \
$(MBEDTLS_LIB_DIR)/library/hmac_drbg.o \
$(MBEDTLS_LIB_DIR)/library/md.o \
$(MBEDTLS_LIB_DIR)/library/md_wrap.o \
$(MBEDTLS_LIB_DIR)/library/md2.o \
$(MBEDTLS_LIB_DIR)/library/md4.o \
$(MBEDTLS_LIB_DIR)/library/md5.o \
$(MBEDTLS_LIB_DIR)/library/memory_buffer_alloc.o \
$(MBEDTLS_LIB_DIR)/library/net_sockets.o \
$(MBEDTLS_LIB_DIR)/library/oid.o \
$(MBEDTLS_LIB_DIR)/library/padlock.o \
$(MBEDTLS_LIB_DIR)/library/pem.o \
$(MBEDTLS_LIB_DIR)/library/pk.o \
$(MBEDTLS_LIB_DIR)/library/pk_wrap.o \
$(MBEDTLS_LIB_DIR)/library/pkcs5.o \
$(MBEDTLS_LIB_DIR)/library/pkcs11.o \
$(MBEDTLS_LIB_DIR)/library/pkcs12.o \
$(MBEDTLS_LIB_DIR)/library/pkparse.o \
$(MBEDTLS_LIB_DIR)/library/pkwrite.o \
$(MBEDTLS_LIB_DIR)/library/platform.o \
$(MBEDTLS_LIB_DIR)/library/ripemd160.o \
$(MBEDTLS_LIB_DIR)/library/rsa.o \
$(MBEDTLS_LIB_DIR)/library/sha1.o \
$(MBEDTLS_LIB_DIR)/library/sha256.o \
$(MBEDTLS_LIB_DIR)/library/sha512.o \
$(MBEDTLS_LIB_DIR)/library/ssl_cache.o \
$(MBEDTLS_LIB_DIR)/library/ssl_ciphersuites.o \
$(MBEDTLS_LIB_DIR)/library/ssl_cli.o \
$(MBEDTLS_LIB_DIR)/library/ssl_cookie.o \
$(MBEDTLS_LIB_DIR)/library/ssl_srv.o \
$(MBEDTLS_LIB_DIR)/library/ssl_ticket.o \
$(MBEDTLS_LIB_DIR)/library/ssl_tls.o \
$(MBEDTLS_LIB_DIR)/library/threading.o \
$(MBEDTLS_LIB_DIR)/library/timing.o \
$(MBEDTLS_LIB_DIR)/library/version.o \
$(MBEDTLS_LIB_DIR)/library/version_features.o \
$(MBEDTLS_LIB_DIR)/library/x509.o \
$(MBEDTLS_LIB_DIR)/library/x509_create.o \
$(MBEDTLS_LIB_DIR)/library/x509_crl.o \
$(MBEDTLS_LIB_DIR)/library/x509_crt.o \
$(MBEDTLS_LIB_DIR)/library/x509_csr.o \
$(MBEDTLS_LIB_DIR)/library/x509write_crt.o \
$(MBEDTLS_LIB_DIR)/library/x509write_csr.o \
$(MBEDTLS_LIB_DIR)/library/xtea.o 

INCLUDE_PATHS += -I$(MBEDTLS_ROOT_DIR)/ -I$(MBEDTLS_LIB_DIR)/include/  -I$(SRCDIR)/library

C_OBJ += $(MBEDTLS_OBJ)