#
#
#

PQUIC_OBJ += $(PICOQUIC_LIB_DIR)/lib/cubic.o \
	$(PICOQUIC_LIB_DIR)/lib/democlient.o \
    $(PICOQUIC_LIB_DIR)/lib/demoserver.o \
    $(PICOQUIC_LIB_DIR)/lib/fnv1a.o \
    $(PICOQUIC_LIB_DIR)/lib/frames.o \
    $(PICOQUIC_LIB_DIR)/lib/h3zero.o \
    $(PICOQUIC_LIB_DIR)/lib/http0dot9.o \
    $(PICOQUIC_LIB_DIR)/lib/intformat.o \
    $(PICOQUIC_LIB_DIR)/lib/logger.o \
    $(PICOQUIC_LIB_DIR)/lib/newreno.o \
    $(PICOQUIC_LIB_DIR)/lib/packet.o \
    $(PICOQUIC_LIB_DIR)/lib/picohash.o \
    $(PICOQUIC_LIB_DIR)/lib/picosocks.o \
    $(PICOQUIC_LIB_DIR)/lib/picosplay.o \
    $(PICOQUIC_LIB_DIR)/lib/quicctx.o \
    $(PICOQUIC_LIB_DIR)/lib/sacks.o \
    $(PICOQUIC_LIB_DIR)/lib/sender.o \
    $(PICOQUIC_LIB_DIR)/lib/spinbit.o \
    $(PICOQUIC_LIB_DIR)/lib/ticket_store.o \
    $(PICOQUIC_LIB_DIR)/lib/token_store.o \
    $(PICOQUIC_LIB_DIR)/lib/tls_api.o \
    $(PICOQUIC_LIB_DIR)/lib/transport.o \
    $(PICOQUIC_LIB_DIR)/lib/util.o


INCLUDE_PATHS += -I$(PICOQUIC_ROOT_DIR)/ -I$(PICOQUIC_LIB_DIR)/include/ -I$(PICOTLS_ROOT_DIR)/

#CC_SYMBOLS += -DPICOQUIC_USER_SETTINGS

#C_OBJ += $(PQUIC_OBJ)

